[features]
seeds = false
skip-lint = false
[programs.localnet]
marketplace_solana_2023 = "4pnzxTjn7VxS2fBj3H3ESzxrRhrAdzu79TwQ73LnxgW6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/savvy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
